[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/.next"

[build.environment]
  NEXT_PUBLIC_API_URL = ""
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyCQhXzRAyp0pxAVI2oyeBnNZO7hIf7lMzU"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "yznotebooklm.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "yznotebooklm"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "yznotebooklm.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "1029038673460"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:1029038673460:web:5136a5447dfced5cacc461"

[[plugins]]
  package = "@netlify/plugin-nextjs"
