[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/.next"

[build.environment]
  NEXT_PUBLIC_API_URL = ""
  NEXT_PUBLIC_FIREBASE_API_KEY = ""
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = ""
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"
